export * from "./auth";
export * from "./error";
export * from "./doctor";
export * from "./quotes";
export * from "./appointment";
export * from "./category";
export * from "./profile";
export * from "./patinets";
export * from "./test"